config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        get '/photos',   to: 'photos#index'
        resources :comments, only: :index, module: :users
      end
      resources :photos, only: [:index, :create, :show] do
        resources :comments, only: [:create, :index], module: :photos
        resources :likes, only: :create
      end
    end
  end

  root 'photos#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'photos', to: 'photos#index', as: 'user_photos'
  post 'photos', to: 'photos#create'

  get 'instagram_search', to: 'photos#instagram_search'
  get '/users/:user_id/photo_collection', to: 'photos#show_collection', as: 'current_user_photo_collection'
  get 'photo/:id', to: 'photos#show', as: 'photo'
  get '/user/:user_id/photo/:photo_id/comment/:parent_comment_id/comments/new', to: 'comments#new', as: 'new_user_photo_comment_comments'
  post '/user/:user_id/photo/:photo_id/comment/:parent_comment_id/comments', to: 'comments#create', as: 'user_photo_comment_comments'

  
  resources :users do
    resources :photos, except: [:index, :create] do
      resources :comments 
      resources :likes, only: [:create]
    end
  end
  
  
  
  
  

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  body              :text
#  user_id           :integer
#  photo_id          :integer
#  parent_comment_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_comments_on_parent_comment_id  (parent_comment_id)
#  index_comments_on_photo_id           (photo_id)
#  index_comments_on_user_id            (user_id)
#

class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo

  has_many   :sub_comments, class_name: 'Comment', foreign_key: 'parent_comment_id'
  belongs_to :parent_comment, class_name: 'Comment', foreign_key: 'parent_comment_id'
end

app/controllers/api/v1/comments_controller.rb
# ...
module API
  # ...
  module V1
    # ...
    class CommentsController < ApplicationController
      layout false
      before_action :autorization, only: :create

      def create
        photo = Photo.find(params[:photo_id])
        outcome = Comments::Create.run(photo: photo, user: current_user, body: params[:body],
                                       parent_comment_id: params[:parent_comment_id])
        if outcome.success?
          render nothing: true, status: 201
        else
          render json: outcome.errors.symbolic, status: 422
        end
      end
    end
  end
end

app/controllers/api/v1/photos/comments_controller.rb
# ...
module API
  # ...
  module V1
    # ...
    module Photos
      class CommentsController < ApplicationController
        layout false

        def index
          comments = Comment.where(photo_id: params[:photo_id], parent_comment_id: nil)
          render json: comments, status: 200
        end
      end
    end
  end
end

app/controllers/api/v1/users/comments_controller.rb
# ...
module API
  # ...
  module V1
    # ...
    module Users
      class CommentsController < ApplicationController
        layout false

        def index
          comments = Comment.where(user_id: params[:user_id])
          render json: comments, user_id: params[:user_id], status: 200
        end
      end
    end
  end
end

app/controllers/comments_controller.rb
# Controller for comments
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    photo = Photo.find(params[:photo_id])
    outcome = Comments::Create.run(photo: photo, user: current_user,
                                   body: params[:comment]['body'],
                                   parent_comment_id: params[:parent_comment_id])
    if outcome.success?
      flash[:success] = 'Комментарий добавлен!'
      redirect_to root_path
    else
      render html: outcome.errors.message
    end
  end
end

app/helpers/comments_helper.rb
# ...
module CommentsHelper
end

app/views/comments/_comment.haml
.comment
  - comment.body.each_line do |line|
    %span.comment_body
      = line
    %br/
  - user = User.find(comment.user_id.to_i)
  %span.sub_comment
    Дата публикации: #{comment.created_at} Автор комментария: #{user.name}
  - if current_user
    %span.sub_comment= link_to 'Ответить на комментарий', new_user_photo_comment_comments_path(parent_comment_id: comment, user_id: current_user, photo_id: comment.photo_id)
  = render partial: '/comments/comment', collection: comment.sub_comments if comment.sub_comments

app/views/comments/new.haml
Оставьте свой ответ на следующий комментарий:
- parent_comment = Comment.find(params[:parent_comment_id])
- photo = Photo.find(params[:photo_id])
- parent_comment.body.each_line do |line|
  %br/
  %span
    = line
= form_for ([current_user, photo, parent_comment, photo.comments.build]) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2
        = @comment.errors.count
        ошибки при сохранении записи:
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg
  %br/
  %p
    = f.label 'Оставьте вашe сообщение'
    %br/
    = f.text_area :body, size: "40x5"
  %p
    = f.submit 'Отправить', class: 'btn btn-primary'