config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        get '/photos',   to: 'photos#index'
        resources :comments, only: :index, module: :users
      end
      resources :photos, only: [:index, :create, :show] do
        resources :comments, only: [:create, :index], module: :photos
        resources :likes, only: :create
      end
    end
  end

  root 'photos#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'photos', to: 'photos#index', as: 'user_photos'
  post 'photos', to: 'photos#create'

  get 'instagram_search', to: 'photos#instagram_search'
  get '/users/:user_id/photo_collection', to: 'photos#show_collection', as: 'current_user_photo_collection'
  get 'photo/:id', to: 'photos#show', as: 'photo'
  get '/user/:user_id/photo/:photo_id/comment/:parent_comment_id/comments/new', to: 'comments#new', as: 'new_user_photo_comment_comments'
  post '/user/:user_id/photo/:photo_id/comment/:parent_comment_id/comments', to: 'comments#create', as: 'user_photo_comment_comments'

  
  resources :users do
    resources :photos, except: [:index, :create] do
      resources :comments 
      resources :likes, only: [:create]
    end
  end
  
  
  
  
  

end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id          :integer          not null, primary key
#  name        :string
#  photo       :string
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  likes_count :integer          default(0)
#  aasm_state  :string
#
# Indexes
#
#  index_photos_on_user_id                 (user_id)
#  index_photos_on_user_id_and_created_at  (user_id,created_at)
#

class Photo < ActiveRecord::Base
  include AASM

  self.per_page = 10

  belongs_to :user
  has_many   :comments, dependent: :destroy
  has_many   :likes,    dependent: :destroy
  default_scope     -> { order(created_at: :desc) }
  scope :filtered_by_user_sub_name, -> (sub_name) { joins(:user).where('users.name ILIKE ?', "%#{sub_name}%") }
  scope :searched,  ->(name) { where('photos.name ILIKE ?', "%#{name}%") }
  scope :from_user, ->(user_id) { where(user_id: user_id) }
  scope :recent,    -> { reorder(created_at: :desc).limit(3) }
  scope :popular,   -> { reorder(likes_count: :desc).limit(3) }

  mount_uploader :photo, PhotographyUploader

  aasm do # default column: aasm_state
    state :moderated, initial: true
    state :approved
    state :banned

    event :approve do
      transitions from: [:moderated, :banned], to: :approved
    end

    event :ban do
      transitions from: [:moderated, :approved], to: :banned
    end
  end
end

app/controllers/api/v1/photos/comments_controller.rb
# ...
module API
  # ...
  module V1
    # ...
    module Photos
      class CommentsController < ApplicationController
        layout false

        def index
          comments = Comment.where(photo_id: params[:photo_id], parent_comment_id: nil)
          render json: comments, status: 200
        end
      end
    end
  end
end

app/controllers/api/v1/photos_controller.rb
# ...
module API
  # ...
  module V1
    # ...
    class PhotosController < ApplicationController
      layout false
      before_action :autorization, only: :create

      def create
        outcome = Photos::Create.run(name: params[:name],
                                     photo: params[:photo], user: current_user)
        if outcome.success?
          render nothing: true, status: 201
        else
          render json: outcome.errors.symbolic, status: 422
        end
      end

      def index
        photos = Photo.approved
        photos = photos.searched(params[:search]) if params[:search].present?
        photos = photos.from_user(params[:user_id]) if params[:user_id].present?
        photos = photos.recent if params.include?(:recent)
        photos = photos.popular if params.include?(:popular)
        render json: photos, status: 200
      end

      def show
        photo = Photo.approved.find(params[:id])
        render json: photo, status: 200
      end

    end
  end
end

app/controllers/photos_controller.rb
# Controller for photography
class PhotosController < ApplicationController
  def index
    @photos = Photo.approved.page(params[:page])
    @photos = @photos.reorder(params[:sorting]) if params[:sorting].present?
    @photos = @photos.filtered_by_user_sub_name(params[:search_by_users_name]) if params[:search_by_users_name].present?
  end

  def new
    @photo = Photo.new
  end

  def create
    outcome = Photos::Create.run(photo_params.merge(user: current_user))
    if outcome.success?
      @photo = outcome.result
      flash[:success] = 'Фотография отправлена на модерацию!'
      redirect_to root_path
    else
      flash[:warning] = "Возникли ошибки при передаче фото на сервер #{outcome.errors.message}"
      redirect_to request.referer
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def show_collection
    @photos = Photo.where(user_id: current_user, aasm_state: [:approved, :moderated]).page(params[:page])
  end

  def instagram_search
    @client = Instagram.client(access_token: ENV['ACCESS_TOKEN'])
    @images_url = []
    @tag = (params[:q].split)[0]
    for media_item in @client.tag_recent_media(URI.encode(@tag), count: 50)
      @images_url << media_item.images.thumbnail.url
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:name, :photo)
  end
end

app/helpers/photos_helper.rb
# ...
module PhotosHelper
end

app/views/photos/_flash_message.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}", :style => "position: relative;"}
    = value

app/views/photos/_like.haml
= form_for [current_user, photo, photo.likes.build] do |f|
  = f.submit 'LIKE THIS',  class: 'btn btn-link'

app/views/photos/_photo.haml
- @photo = photo
.jumbotron
  %table
    %tr
      %td{:align => "middle", :valign => "top", :width => "220"}
        = link_to (image_tag @photo.photo.thumb), photo_path(@photo.id)
        %br/
        = @photo.name
        %br/
        = "Автор фото: #{User.find(@photo.user_id).name}"
      %td{:align => "middle", :valign => "top", :width => "165"}
        - if @photo.aasm_state == 'approved'
          %h7 Количество
          %br/
          %h7 голосов:
          %br/
          %h2{id: "photo_#{@photo.id}_likes_count"}
            = @photo.likes_count
          - if current_user
            = render partial: 'like', locals: {photo: @photo}
        - elsif @photo.aasm_state == 'moderated'
          Фото на модерации
      %td{:align => "left", :valign => "top", :width => "60%"}
        - if @photo.comments.any?
          %p{:align => "center"} Последние комментарии:
          - @comments = @photo.comments.order(created_at: :asc).where(parent_comment_id: nil).limit(3)
          = render partial: '/comments/comment', collection: @comments, as: :comment
        - else
          %p{:align => "center"} Комментариев пока нет, оставьте первый комментарий
        - if current_user
          .comment_field
            = form_for([current_user, @photo, @photo.comments.build]) do |f|
              %p{:align => "right"}
                = f.label 'Оставьте ваш комментарий'
                %br/
                = f.text_area :body
              %p{:align => "right"}
                = f.submit 'Разместить новый комментарий', class: 'btn btn-primary'

app/views/photos/_photo_show.haml
.jumbotron
  %div{:align => "center"}
    = image_tag photo.photo
    %br/
    %hr/
    %table{:width => "100%"}
      %tr
        %td{:width => "65%"}
          = photo.name
          %br/
          - user = User.find(photo.user_id)
          Автор фото: #{user.name}
        %td{:align => "right", :width => "15%"}
          - if photo.likes_count == 0
            %h7 За данное фото
            %br/
            %h7 еще не голосовали
          - else
            %h7 Количество
            %br/
            %h7 голосов:
        %td{:align => "center", :width => "10%"}
          %span= photo.likes_count
        %td{:width => "10%"}
          - if current_user
            = form_for ([current_user, photo, photo.likes.build]) do |f|
              = f.submit 'LIKE THIS',  class: 'btn btn-link'
    %hr/
  %table{:width => "100%"}
    %tr
      %td
        - if photo.comments.any?
          %p{:align => "center"} Последние комментарии:
          - @comments = photo.comments.order(created_at: :asc).where(parent_comment_id: nil)
          = render partial: '/comments/comment', collection: @comments, as: :comment
        - else
          %h5{:align => "right"} Комментариев пока нет, оставьте первый комментарий
    %tr
      %td
        - if current_user
          = form_for([current_user, photo, photo.comments.build]) do |f|
            %p{:align => "right"}
              = f.label 'Оставьте ваш комментарий'
              %br/
              = f.text_area :body
            %p{:align => "right"}
              = f.submit 'Разместить новый комментарий', class: 'btn btn-primary'

app/views/photos/_search_tag.haml
= form_tag("instagram_search", method: "get") do
  = label_tag(:q, "Найти фото по хэш-тегу:")
  %br/
  = text_field_tag(:q)
  = submit_tag("Найти")

app/views/photos/_search_user.haml
= form_tag(user_photos_path, method: "get") do
  = label_tag(:search_by_users_name, "Найти фото по автору:")
  %br/
  = text_field_tag(:search_by_users_name)
  = submit_tag("Найти")

app/views/photos/_sorting.haml
Упорядочить фото по:
%br/
= link_to 'дате (вверху старые)', user_photos_path(sorting: 'created_at ASC', search_by_users_name: params[:search_by_users_name] ? params[:search_by_users_name] : nil)
= link_to 'дате (вверху новые)', user_photos_path(sorting: 'created_at DESC',  search_by_users_name: params[:search_by_users_name] ? params[:search_by_users_name] : nil) 
= link_to 'голосам (вверху большие)', user_photos_path(sorting: 'likes_count DESC',  search_by_users_name: params[:search_by_users_name] ? params[:search_by_users_name] : nil)
= link_to 'голосам (вверху меньшие)', user_photos_path(sorting: 'likes_count ASC',  search_by_users_name: params[:search_by_users_name] ? params[:search_by_users_name] : nil)

app/views/photos/_sorting_and_search.haml
.jimbotron
  %table{:valign => "middle", :width => "100%"}
    %tr
      %td{:height => "80em"}
        = render 'sorting'
      %td{:align => "right"}
        = render 'search_tag'
      %td{:align => "right"}
        = render 'search_user'

app/views/photos/index.haml
= render 'photos/sorting_and_search'
= will_paginate @photos
= render @photos
= will_paginate @photos

app/views/photos/instagram_search.haml
.jimbotron
  = render 'search_tag'
  %br/
  %h2
    = "Картинки, найденные по тегу '#{@tag}':"
  %br/
  - @images_url.each do |image|
    = image_tag image

app/views/photos/new.haml
= form_for :photo, url: user_photos_path do |f|
  - if @photo.errors.any?
    #error_explanation
      %h2
        = @photo.errors.count
        ошибки при сохранении записи:
      %ul
        - @photo.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label 'Введите подпись к фотографии:'
    %br/
    = f.text_field :name
  %p
    = f.label 'Выберите файл:'
    %br/
    = f.file_field :photo, accept: 'image/jpeg,image/gif,image/png'
  = f.submit "Отправить", class: "btn btn-primary"

app/views/photos/show.haml
= render 'photo_show', photo: @photo

app/views/photos/show_collection.haml
= will_paginate @photos
= render @photos
= will_paginate @photos