config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        get '/photos',   to: 'photos#index'
        resources :comments, only: :index, module: :users
      end
      resources :photos, only: [:index, :create, :show] do
        resources :comments, only: [:create, :index], module: :photos
        resources :likes, only: :create
      end
    end
  end

  root 'photos#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'photos', to: 'photos#index', as: 'user_photos'
  post 'photos', to: 'photos#create'

  get 'instagram_search', to: 'photos#instagram_search'
  get '/users/:user_id/photo_collection', to: 'photos#show_collection', as: 'current_user_photo_collection'
  get 'photo/:id', to: 'photos#show', as: 'photo'
  get '/user/:user_id/photo/:photo_id/comment/:parent_comment_id/comments/new', to: 'comments#new', as: 'new_user_photo_comment_comments'
  post '/user/:user_id/photo/:photo_id/comment/:parent_comment_id/comments', to: 'comments#create', as: 'user_photo_comment_comments'

  
  resources :users do
    resources :photos, except: [:index, :create] do
      resources :comments 
      resources :likes, only: [:create]
    end
  end
  
  
  
  
  

end

app/views/layouts/application.haml
!!!
%html
  %head
    %title PhotoContest
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse
      .container
        .navbar-header
          = link_to 'Фотоконкурс', root_path, class: 'navbar-brand'
        #navbar
          - if current_user
            %ul.nav.navbar-nav.pull-right
              %li= link_to 'Добавить новое фото', new_user_photo_path(current_user.id)
              %li= link_to 'Посмотреть свои фото', current_user_photo_collection_path(current_user.id)
              %li= image_tag current_user.image_url, alt: current_user.name
              %li= link_to 'Выйти', logout_path, method: :delete
          - else
            %ul.nav.navbar-nav
              %li= link_to 'Facebook', '/auth/facebook'
              %li= link_to 'Вконтакте', '/auth/vkontakte'
              %li= link_to 'Instagram', '/auth/instagram'
    .container
      = render 'photos/flash_message'
      = yield